export { createDb } from './client.js';
export type { DbConfig } from './client.js';
export type {
  Database,
  // New tables (001–009)
  PlcOperationTable,
  SystemConfigTable,
  FactLogTable,
  FactLogRedactionTable,
  DataDeletionRequestTable,
  EntityTable,
  CooperativeProfileTable,
  EntityKeyTable,
  AuthCredentialTable,
  SessionTable,
  PdsRecordTable,
  PdsCommitTable,
  PdsFirehoseCursorTable,
  InvitationTable,
  MembershipTable,
  MembershipRoleTable,
  ThreadTable,
  ThreadMemberTable,
  PostTable,
  ProposalTable,
  VoteTable,
  AgreementTable,
  AgreementSignatureTable,
  AgreementRevisionTable,
  AgreementTemplateTable,
  // Legacy tables
  StakeholderInterestTable,
  DesiredOutcomeTable,
  InterestMapTable,
  StakeholderTermsTable,
  ExternalConnectionTable,
  ConnectionBindingTable,
  FundingCampaignTable,
  FundingPledgeTable,
  OidcClientTable,
  OidcPayloadTable,
  OidcConsentTable,
  AgentConfigTable,
  AgentSessionTable,
  AgentMessageTable,
  AgentUsageTable,
  AgentTriggerTable,
  TriggerExecutionLogTable,
  NotificationTable,
  DelegationTable,
  // V5 tables (030)
  PrivateRecordTable,
  OperatorAuditLogTable,
  // Legal & Administrative (033)
  LegalDocumentTable,
  MeetingRecordTable,
  AdminOfficerTable,
  ComplianceItemTable,
  MemberNoticeTable,
  FiscalPeriodTable,
  // Financial tools (035)
  PatronageConfigTable,
  PatronageRecordTable,
  CapitalAccountTable,
  CapitalAccountTransactionTable,
  TaxForm1099PatrTable,
  // Onboarding tables (031)
  OnboardingConfigTable,
  OnboardingProgressTable,
  OnboardingReviewTable,
  // Weighted voting + cooperative links (032)
  MemberClassTable,
  CooperativeLinkTable,
  // Operations — Phase 8 (038–042)
  TaskTable,
  TaskLabelTable,
  TaskChecklistItemTable,
  TimeEntryTable,
  ScheduleShiftTable,
  ExpenseCategoryTable,
  ExpenseTable,
  RevenueEntryTable,
  // Commerce & Integration — Phase 9 (043–048)
  CommerceListingTable,
  CommerceNeedTable,
  IntercoopAgreementTable,
  CollaborativeProjectTable,
  CollaborativeContributionTable,
  SharedResourceTable,
  ResourceBookingTable,
  ProcurementGroupTable,
  ProcurementDemandTable,
  ConnectorConfigTable,
  ConnectorSyncLogTable,
  ConnectorFieldMappingTable,
  WebhookEndpointTable,
  WebhookDeliveryLogTable,
} from './schema.js';
