export { createDb } from './client.js';
export type { DbConfig } from './client.js';
export type {
  Database,
  // New tables (001–009)
  PlcOperationTable,
  SystemConfigTable,
  FactLogTable,
  FactLogRedactionTable,
  DataDeletionRequestTable,
  EntityTable,
  CooperativeProfileTable,
  EntityKeyTable,
  AuthCredentialTable,
  SessionTable,
  PdsRecordTable,
  PdsCommitTable,
  PdsFirehoseCursorTable,
  InvitationTable,
  MembershipTable,
  MembershipRoleTable,
  ThreadTable,
  ThreadMemberTable,
  PostTable,
  ProposalTable,
  VoteTable,
  AgreementTable,
  AgreementSignatureTable,
  AgreementRevisionTable,
  AgreementTemplateTable,
  // Legacy tables
  StakeholderInterestTable,
  DesiredOutcomeTable,
  InterestMapTable,
  StakeholderTermsTable,
  ExternalConnectionTable,
  ConnectionBindingTable,
  FundingCampaignTable,
  FundingPledgeTable,
  OidcClientTable,
  OidcPayloadTable,
  OidcConsentTable,
  AgentConfigTable,
  AgentSessionTable,
  AgentMessageTable,
  AgentUsageTable,
  AgentTriggerTable,
  TriggerExecutionLogTable,
  NotificationTable,
  DelegationTable,
  // V5 tables (030)
  PrivateRecordTable,
  OperatorAuditLogTable,
  // Legal & Administrative (033)
  LegalDocumentTable,
  MeetingRecordTable,
  AdminOfficerTable,
  ComplianceItemTable,
  MemberNoticeTable,
  FiscalPeriodTable,
  // Financial tools (035)
  PatronageConfigTable,
  PatronageRecordTable,
  CapitalAccountTable,
  CapitalAccountTransactionTable,
  TaxForm1099PatrTable,
} from './schema.js';
