export { createDb } from './client.js';
export type { DbConfig } from './client.js';
export type {
  Database,
  // New tables (001–009)
  PlcOperationTable,
  SystemConfigTable,
  FactLogTable,
  FactLogRedactionTable,
  DataDeletionRequestTable,
  EntityTable,
  CooperativeProfileTable,
  EntityKeyTable,
  AuthCredentialTable,
  SessionTable,
  PdsRecordTable,
  PdsCommitTable,
  PdsFirehoseCursorTable,
  InvitationTable,
  MembershipTable,
  MembershipRoleTable,
  ThreadTable,
  ThreadMemberTable,
  PostTable,
  ProposalTable,
  VoteTable,
  AgreementTable,
  AgreementPartyTable,
  AgreementSignatureTable,
  // Legacy tables
  StakeholderInterestTable,
  DesiredOutcomeTable,
  InterestMapTable,
  MasterAgreementTable,
  StakeholderTermsTable,
  ExternalConnectionTable,
  ConnectionBindingTable,
  AutomationWorkflowTable,
  AutomationTriggerTable,
  FundingCampaignTable,
  FundingPledgeTable,
  OidcClientTable,
  OidcPayloadTable,
  OidcConsentTable,
  EventLogTable,
  WorkflowExecutionTable,
  AgentConfigTable,
  AgentSessionTable,
  AgentMessageTable,
  AgentUsageTable,
  DelegationTable,
} from './schema.js';
